-- plugins
require('user.bufferline')
require('user.cmp')
require('user.commands')
-- require('user.copilot')
require('user.dressing')
require('user.gitsigns')
require('user.indent-blankline')
require('user.jdtls')
require('user.lspconfig')
require('user.lualine')
require('user.luasnip')
require('user.mini')
require('user.navic')
require('user.neotree')
require('user.null-ls')
require('user.settings')
require('user.telescope')
require('user.todo-comments')
require('user.tree-sitter')
require('user.whichkey')

-- theme goes the last one
require('user.catppuccin')
